version: '3'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  app:
    container_name: recruiting-and-selection-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - PORT=8080
      - MONGO_URL=$MONGO_URL
      - PATH_API=$PATH_API
    ports:
      - 8080:8080
    depends_on:
      - mongodb
